name: Build and deploy Docker image to Azure Web App - 525kk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_USERNAME }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Pull Docker image
        run: docker pull mirotalk/p2p:latest

      - name: Create Docker Compose file
        run: |
          echo "version: '3.8'
          services:
            mirotalk:
              image: mirotalk/p2p:latest
              ports:
                - 3000:3000
              environment:
                - PORT=3000
                - NODE_ENV=production
          " > docker-compose.yml

      - name: Zip artifact for deployment
        run: zip release.zip docker-compose.yml

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-artifact
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: docker-compose-artifact

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: '525kk'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_133DC00ABFC848EFB06B3A632EBF3861 }}

      - name: Start Docker Compose
        run: docker-compose up -d
